[package]
name = "parameter-box"
version = "0.1.0"
authors=["Yuichi Ishida"]
edition = "2018"
license = "MIT"
description = "This is the library for reading parameters from files."
readme = "README.md"
repository = "https://github.com/yu1guana/parameter-box-rust"


[dependencies]
